#pragma once

#include "log/Log.h"
#include <algorithm>
#include <chrono>
#include <deque>
#include <functional>
#include <iostream>
#include <map>
#include <memory>
#include <mutex>
#include <queue>
#include <sstream>
#include <thread>
#include <vector>
#include <any>

using std::cout;
using std::deque;
using std::endl;
using std::function;
using std::make_shared;
using std::map;
using std::multimap;
using std::mutex;
using std::ostringstream;
using std::queue;
using std::shared_ptr;
using std::string;
using std::thread;
using std::uint8_t;
using std::unique_ptr;
using std::vector;
using std::weak_ptr;
using std::any;
using std::any_cast;
